version: "3.8"

services:
  db:
    image: postgres:16-alpine
    volumes:
      - ${DATA_PATH}:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - vampire

  web:
    build: ./BE
    volumes:
      - ./BE:/app
    expose:
      - "3001:3001"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - vampire

  nginx:
    build: ./FE
    ports:
      - "80:80"
    volumes: # 나중에 삭제
      - ./FE:/usr/share/nginx/html
    depends_on:
      - web
    networks:
      - vampire

networks:
  vampire:
    driver: bridge