# Generated by Django 4.2.13 on 2024-07-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0006_message_blockedrelationship'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('user', 'friend'), name='unique_friendship'),
        ),
    ]
