# Generated by Django 4.2.13 on 2024-07-03 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0007_friendship_unique_friendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockedrelationship',
            name='blocked_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_user', to='lobby.user'),
        ),
        migrations.AlterField(
            model_name='blockedrelationship',
            name='blocker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to='lobby.user'),
        ),
    ]
