version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - vampire

  # db:
  #   image: postgres:13
  #   volumes:
  #     - ${DATA_PATH}:/var/lib/postgresql/data
  #   env_file:
  #     - .env
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - vampire

# networks:
#   vampire:
#     driver: bridge
