version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "3001:3001"
  # postgres:
  #   container_name: postgres-server
  #   image: postgres:15
  #   restart: always
  #   volumes:
  #     - ${DATA_PATH}:/var/lib/postgresql/data
  #     - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: pingpong